---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop 
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"


---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels: #labels used to find pods
      app: cart
      project: roboshop
      tier: app

  template: #it's the pod definition section 
    metadata:
      labels: #pod labels
        app: cart
        project: roboshop
        tier: app
    spec:
      containers: 
      - name: cart
        image: dockerlearnsrikanth/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 #serviceport
      targetPort: 8080 #containerport



