apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels: #labels used to find pods
      app: mongodb
      project: roboshop
      tier: db

  template: #it's the pod definition section 
    metadata:
      labels: #pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers: 
      - name: mongodb
        image: dockerlearnsrikanth/mongodb:v1
        imagePullPolicy: Always



---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #serviceport
      targetPort: 27017 #containerport


