---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop 
data:
  MONGO: "true"


---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    project: roboshop
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels: #labels used to find pods
      app: user
      project: roboshop
      tier: app

  template: #it's the pod definition section 
    metadata:
      labels: #pod labels
        app: user
        project: roboshop
        tier: app
    spec:
      containers: 
      - name: user
        image: dockerlearnsrikanth/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 #serviceport
      targetPort: 8080 #containerport



