apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels: #labels used to find pods
      app: redis
      project: roboshop
      tier: db

  template: #it's the pod definition section 
    metadata:
      labels: #pod labels
        app: redis
        project: roboshop
        tier: db
    spec:
      containers: 
      - name: redis
        image: redis
        imagePullPolicy: Always



---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 6379 #serviceport
      targetPort: 6379 #containerport


